#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include "function.h"
#include "stm32f10x.h"
#include "stm32f10x_usart.h"
#include "stm32f10x_gpio.h"
#include "stm32f10x_rcc.h"
#include "misc.h"
#include "crc16.h"
